env:
  browser: true
  commonjs: true
  node: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 2018
  sourceType: 'module'
rules:
  indent:
    - error
    - 4
  quotes:
    - error
    - single
  semi:
    - error
    - never
  no-trailing-spaces:
    - error
